import type { Font } from "opentype.js";
import { layoutText } from "./textToShapes";

export interface PathBounds {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
}

const NUMBER = /[-+]?(?:\d+\.?\d*|\.\d+)(?:e[-+]?\d+)?/gi;

/**
 * Bounding box of the points of a path made of absolute M/L/Q/C/Z commands (what `layoutText` writes): every
 * coordinate pair, control points included. Curves may bulge a little inside the control polygon, so the box can
 * be a hair larger than the ink, never smaller. `null` when there are no coordinates.
 */
export function pathBounds(d: string): PathBounds | null {
  const nums = (d.match(NUMBER) ?? []).map(Number);
  if (nums.length < 2) return null;
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (let i = 0; i + 1 < nums.length; i += 2) {
    const x = nums[i];
    const y = nums[i + 1];
    if (x < minX) minX = x;
    if (x > maxX) maxX = x;
    if (y < minY) minY = y;
    if (y > maxY) maxY = y;
  }
  return [minX, minY, maxX, maxY].every(Number.isFinite) ? { minX, minY, maxX, maxY } : null;
}

const MAX_SLUG = 32;

/** `sunlite-text-<slug>.svg`, where the slug is the typed text flattened to lowercase letters, digits and dashes. */
export function textArtworkFileName(text: string): string {
  const slug = text
    .normalize("NFKD")
    .replace(/\p{M}/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, MAX_SLUG)
    .replace(/-+$/g, "");
  return `sunlite-text-${slug || "text"}.svg`;
}

const escapeXml = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&apos;");

const round = (n: number) => String(Number(n.toFixed(2)));

interface TextSvgInput {
  /** The text outlines as one SVG path (y-down), as produced by `layoutText`. */
  pathData: string;
  /** What was typed, quoted in the file's title. */
  text: string;
  fontLabel: string;
}

/** A standalone SVG of the text outlines with a viewBox that fits them; `null` when there is nothing to draw. */
export function buildTextArtworkSvg({ pathData, text, fontLabel }: TextSvgInput): string | null {
  const b = pathBounds(pathData);
  if (!b) return null;
  const w = b.maxX - b.minX;
  const h = b.maxY - b.minY;
  if (!(w > 0) || !(h > 0)) return null;

  const quoted = text
    .split(/\r?\n/)
    .map((l) => l.replace(/\p{Cc}/gu, " ").trim())
    .filter(Boolean)
    .join(" / ")
    .slice(0, 120);
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${round(b.minX)} ${round(b.minY)} ${round(w)} ${round(h)}" width="${round(w)}" height="${round(h)}">`,
    `<title>${escapeXml(`Sign text: ${quoted}`)}</title>`,
    `<desc>${escapeXml(`Text outlines in ${fontLabel}, generated by the Sunlite sign configurator.`)}</desc>`,
    `<path fill="#000000" fill-rule="nonzero" d="${pathData}"/>`,
    "</svg>",
    "",
  ].join("\n");
}

/** The typed text as an SVG file of letter outlines, so the factory gets usable artwork; `null` if nothing is drawable. */
export function createTextArtworkFile(text: string, font: Font, fontLabel: string): File | null {
  const { pathData } = layoutText(text, font);
  if (pathData === "") return null;
  const svg = buildTextArtworkSvg({ pathData, text, fontLabel });
  return svg ? new File([svg], textArtworkFileName(text), { type: "image/svg+xml" }) : null;
}
